spring:
  # h2 DB 설정
  datasource:
    url: jdbc:mysql://localhost:3306/kjk_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: blue0423
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa 설정
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # devtools 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    mode: HTML5
    cache: false
    prefix: file:src/main/resources/templates/

logging.level:
  org.hibernate.SQL: debug